👍modify: タグ名以外の引数をオプションに変更 📖doc: README.md の記述を修正

diff --git a/brew-base/container-login b/brew-base/container-login
--- a/brew-base/container-login
+++ b/brew-base/container-login
@@ -2,33 +2,89 @@
 
 #-----------------------------------------------------------------------------
 function usage () {
-    echo "$(basename $0) <TAG> [User]" 2>&1;
+echo -e "
+使い方: container-login [OPTION] TAG
+brew-base の新しいコンテナを実行しログインします。
+例: container-login -u 'user' brew-base
+
+\e[33;1m引数:
+    \e[32mTAG
+        \e[37mイメージタグを指定します。
+        DockerHub のアカウント名を使用する形式（'account/brew-base'）
+        もしくはタグ名のみの形式（'brew-base'）を指定することができます。
+
+\e[33;1mオプション:
+    \e[32m-u\e[37m, \e[32m--user <ユーザー名>
+        \e[37m省略可。コンテナで使用するユーザー名を指定します。
+        省略した場合は、現在のホスト側ユーザー名が指定されます。
+\e[m
+" 2>&1;
 }
 
 #-----------------------------------------------------------------------------
 # Docker イメージからコンテナを作成しログインする
 # $1 : タグ名 = DockerHub アカウント名(省略可）/ Dockerfile のあるディレクトリ
 # 例 : xxx/brew-base or brew-base
-# $2 : 作業用ディレクトリとしてマウントするホストのディレクトリパス
 #-----------------------------------------------------------------------------
 EXEC_DIR=$(cd $(dirname $0) && pwd)
 
-set +u
-if [ ${#@} -ne 1 ] && [ ${#@} -ne 2 ]; then
+if [ $# -eq 0 ]; then
+    echo -e "\e[31merror: \e[37m少なくとも1つの引数が必要です。\e[m" >&2;
     usage
     exit 1
 fi
 
-# 引数が"アカウント/ディレクトリ"か"ディレクトリのみ"かを判定する
+VALID_ARGS=$(getopt -o hu: --long help,user: -- "$@")
+# getopt の返り値をチェックして、失敗ならエラー終了
+if [[ $? -ne 0 ]]; then
+    exit 1;
+fi
+
+TAG=
+USERNAME=
+
+eval set -- "${VALID_ARGS}"
+while [ : ]; do
+    case "$1" in
+        -u | --user)
+            USERNAME=$2
+            shift 2
+            ;;
+        -h | --help)
+            usage
+            exit 0
+            ;;
+        --) shift;
+            break
+            ;;
+    esac
+done
+
+# 引数が少ない場合
+if [ $# -lt 1 ]; then
+    echo -e "\e[31merror: \e[37mタグを指定してください。\e[m" >&2;
+    usage
+    exit 1
+# 引数が多すぎる場合
+elif [ $# -gt 1 ]; then
+    echo -e "\e[31merror: \e[37m引数が多すぎます。\e[m" >&2;
+    usage
+    exit 1
+fi
+
 TAG=$1
-USERNAME=$2
+
 set -u
 
+# ユーザーが省略されている場合
 if [ -z "${USERNAME}" ]; then
+    # イメージのビルド時に指定したユーザーを取得
     if [ -e "${EXEC_DIR}/.user" ]; then
         USERNAME=$(cat ${EXEC_DIR}/.user)
     else
         USERNAME=$(whoami)
+        # 次回、ユーザーを省略できるようにファイルを出力
+        echo "${USERNAME}" > ${EXEC_DIR}/.user
     fi
 fi
 
diff --git a/brew-base/image-build b/brew-base/image-build
--- a/brew-base/image-build
+++ b/brew-base/image-build
@@ -2,7 +2,23 @@
 
 #-----------------------------------------------------------------------------
 function usage () {
-    echo "$(basename $0) <TAG> [User]" 2>&1;
+echo -e "
+使い方: image-build [OPTION] TAG
+Ubuntu と Linuxbrew をベースとしたイメージを作成します。
+例: image-build -u 'user' brew-base
+
+\e[33;1m引数:
+    \e[32mTAG
+        \e[37mイメージタグを指定します。
+        DockerHub のアカウント名を使用する形式（'account/brew-base'）
+        もしくはタグ名のみの形式（'brew-base'）を指定することができます。
+
+\e[33;1mオプション:
+    \e[32m-u\e[37m, \e[32m--user <ユーザー名>
+        \e[37m省略可。コンテナで使用するユーザー名を指定します。
+        省略した場合は、現在のホスト側ユーザー名が指定されます。
+\e[m
+" 2>&1;
 }
 
 #-----------------------------------------------------------------------------
@@ -15,11 +31,53 @@ DOCKER_BULDKIT=1
 
 EXEC_DIR=$(cd $(dirname $0) && pwd)
 
+if [ $# -eq 0 ]; then
+    echo -e "\e[31merror: \e[37m少なくとも1つの引数が必要です。\e[m" >&2;
+    usage
+    exit 1
+fi
+
+VALID_ARGS=$(getopt -o hu: --long help,user: -- "$@")
+# getopt の返り値をチェックして、失敗ならエラー終了
+if [[ $? -ne 0 ]]; then
+    exit 1;
+fi
+
+TAG=
+USERNAME=
+
+eval set -- "${VALID_ARGS}"
+while [ : ]; do
+    case "$1" in
+        -u | --user)
+            USERNAME=$2
+            shift 2
+            ;;
+        -h | --help)
+            usage
+            exit 0
+            ;;
+        --) shift;
+            break
+            ;;
+    esac
+done
+
+# 引数が少ない場合
+if [ $# -lt 1 ]; then
+    echo -e "\e[31merror: \e[37mタグを指定してください。\e[m" >&2;
+    usage
+    exit 1
+# 引数が多すぎる場合
+elif [ $# -gt 1 ]; then
+    echo -e "\e[31merror: \e[37m引数が多すぎます。\e[m" >&2;
+    usage
+    exit 1
+fi
+
 set +eu
 # 引数が"アカウント/ディレクトリ"か"ディレクトリのみ"かを判定する
 TAG_NAME=$(echo $1 | grep "/")
-# ユーザー
-USERNAME=$2
 
 # 引数に / が含まれていれば、'/' の前後をアカウント名とディレクトリ名に分ける
 if [ -n "${TAG_NAME}" ]; then
@@ -37,14 +95,16 @@ CPU_CORES=0-$((${NUM_OF_LOGICAL_PROCESSORS} - 1))
 # 利用可能なメモリ
 MEM_LIMIT_GB=$(free -g | sed -n 2p | awk '{ print $7 }')
 
-# ユーザーが省略されている場合は、デフォルトのユーザーを作成する
+# ユーザーが省略されている場合
 if [ -z "${USERNAME}" ]; then
+    # ホスト側の実行ユーザーを取得する
     USERNAME=$(whoami)
     ID=$(id -u "${USERNAME}")
 else
     set +e
     ID=$(id -u "${USERNAME}")
     set -e
+    # ホスト側に存在しないユーザーの場合は UID = 1000
     if [ -z "${ID}" ]; then
         ID=1000
     fi
@@ -61,4 +121,5 @@ docker builder build \
     --build-arg   UID=${ID} \
     "${EXEC_DIR}"
 
+# ユーザー名をキャッシュする
 echo "${USERNAME}" > ${EXEC_DIR}/.user
diff --git a/cli-enhanced/container-login b/cli-enhanced/container-login
--- a/cli-enhanced/container-login
+++ b/cli-enhanced/container-login
@@ -2,49 +2,130 @@
 
 #-----------------------------------------------------------------------------
 function usage () {
-    echo "$(basename $0) <TAG> <Credentials Directory> <Working Directory> [User]" 2>&1;
+echo -e "
+使い方: container-login [OPTION] TAG
+cli-enhanced の新しいコンテナを実行しログインします。
+例: container-login -u 'user' brew-base
+
+\e[33;1m引数:
+    \e[32mTAG
+        \e[37mイメージタグを指定します。
+        DockerHub のアカウント名を使用する形式（'account/cli-enhanced'）
+        もしくはタグ名のみの形式（'cli-enhanced'）を指定することができます。
+
+\e[33;1mオプション:
+    \e[32m-u\e[37m, \e[32m--user <ユーザー名>
+        \e[37m省略可。コンテナで使用するユーザー名を指定します。
+        省略した場合は、現在のホスト側ユーザー名が指定されます。
+    \e[32m-s\e[37m, \e[32m--cred-dir <ユーザー名>
+        \e[37mシークレット情報(.secrets)を保持するホスト側のディレクトリを指定します。
+    \e[32m-d\e[37m, \e[32m--work-dir <ユーザー名>
+        \e[37mホスト側の作業用ディレクトリを指定します。
+\e[m
+" 2>&1;
 }
 
 #-----------------------------------------------------------------------------
 # Docker イメージからコンテナを作成しログインする
 # $1 : タグ名 = DockerHub アカウント名(省略可）/ Dockerfile のあるディレクトリ
 # 例 : xxx/brew-base or brew-base
-# $2 : 作業用ディレクトリとしてマウントするホストのディレクトリパス
 #-----------------------------------------------------------------------------
 EXEC_DIR=$(cd $(dirname $0) && pwd)
 
-set +u
-if [ ${#@} -ne 3 ] && [ ${#@} -ne 4 ]; then
+if [ $# -eq 0 ]; then
+    echo -e "\e[31merror: \e[37m少なくとも1つの引数が必要です。\e[m" >&2;
     usage
     exit 1
 fi
 
-# 引数が"アカウント/ディレクトリ"か"ディレクトリのみ"かを判定する
+VALID_ARGS=$(getopt -o husd: --long help,user:,cred-dir:,work-dir: -- "$@")
+# getopt の返り値をチェックして、失敗ならエラー終了
+if [[ $? -ne 0 ]]; then
+    exit 1;
+fi
+
+TAG=
+USERNAME=
+CREDENTIALS_DIR=
+WORKING_DIR=
+
+eval set -- "${VALID_ARGS}"
+while [ : ]; do
+    case "$1" in
+        -u | --user)
+            USERNAME=$2
+            shift 2
+            ;;
+        -h | --help)
+            usage
+            exit 0
+            ;;
+        -s | --cred-dir)
+            CREDENTIALS_DIR=$2
+            shift 2
+            ;;
+        -d | --work-dir)
+            WORKING_DIR=$2
+            shift 2
+            ;;
+        --) shift;
+            break
+            ;;
+    esac
+done
+
+# 引数が少ない場合
+if [ $# -lt 1 ]; then
+    echo -e "\e[31merror: \e[37mタグを指定してください。\e[m" >&2;
+    usage
+    exit 1
+# 引数が多すぎる場合
+elif [ $# -gt 1 ]; then
+    echo -e "\e[31merror: \e[37m引数が多すぎます。\e[m" >&2;
+    usage
+    exit 1
+fi
+set +u
+
 TAG=$1
-CREDENTIALS_DIR=$2
-WORKING_DIR=$3
-USERNAME=$4
 set -u
 
-# ホスト側のマウントディレクトリを指定しているかを判定する
+# 必須のオプションを使用していない場合
+if [ -z "${CREDENTIALS_DIR}" ]; then
+    echo -e "\e[31merror: \e[37mクレデンシャルディレクトリを指定してください。\e[m" >&2;
+    usage
+    exit 1
+fi
+
+if [ -z "${CREDENTIALS_DIR}" ]; then
+    echo -e "\e[31merror: \e[37m作業用ディレクトリを指定してください。\e[m" >&2;
+    usage
+    exit 1
+fi
+
+# ホスト側のディレクトリを指定しているかを判定する
 if [ ! -d "${CREDENTIALS_DIR}" ]; then
-    echo -e "ERROR: ホスト側のクレデンシャルディレクトリが見つかりません。"
+    echo -e "\e[31merror: \e[37m。ホスト側のクレデンシャルディレクトリが見つかりません。\e[m" >&2;
     usage
     exit 1
 fi
 
 # ホスト側のディレクトリが存在しない場合は、ディレクトリを作成する
 if [ ! -d "${WORKING_DIR}" ]; then
-    echo -e "ERROR: ホスト側の作業用が見つかりません。"
+    echo -e "\e[31merror: \e[37m。ホスト側の作業用ディレクトリが見つかりません。\e[m" >&2;
     usage
     exit 1
 fi
 
+# ユーザーが省略されている場合
 if [ -z "${USERNAME}" ]; then
+    # イメージのビルド時に指定したユーザーを取得
     if [ -e "${EXEC_DIR}/.user" ]; then
         USERNAME=$(cat ${EXEC_DIR}/.user)
     else
         USERNAME=$(whoami)
+        # 次回、ユーザーを省略できるようにファイルを出力
+        echo "${USERNAME}" > ${EXEC_DIR}/.user
     fi
 fi
 
diff --git a/container-login b/container-login
--- a/container-login
+++ b/container-login
@@ -2,7 +2,23 @@
 
 #-----------------------------------------------------------------------------
 function usage () {
-    echo "Usage: [OPTION] $(basename $0) TAG ..."
+echo -e "
+使い方: container-login [OPTION]... TAG
+指定したイメージの新しいコンテナを実行しログインします。
+例: container-login -u 'user' brew-base
+
+\e[33;1m引数:
+    \e[32mTAG
+        \e[37mイメージタグを指定します。
+        DockerHub のアカウント名を使用する形式（'account/tag'）
+        もしくはタグ名のみの形式（'tag'）を指定することができます。
+
+\e[33;1mオプション:
+    \e[32m-u\e[37m, \e[32m--user <ユーザー名>
+        \e[37m省略可。コンテナで使用するユーザー名を指定します。
+        省略した場合は、現在のホスト側ユーザー名が指定されます。
+\e[m
+"
 }
 
 #-----------------------------------------------------------------------------
@@ -13,23 +29,23 @@ function usage () {
 #-----------------------------------------------------------------------------
 EXEC_DIR=$(cd $(dirname $0) && pwd)
 
-set +u
-if [ -z $1 ]; then
+if [ $# -eq 0 ]; then
+    echo -e "\e[31merror: \e[37m少なくとも1つの引数が必要です。\e[m" >&2;
     usage
     exit 1
 fi
 
-if [ $(echo $1 | grep -E "^\-h|^\-\-help$") != ""  ]; then
+# 引数がヘルプオプションだけであれば、ヘルプを表示して終了する
+if [[ $(echo $1 | grep -E "^\-h|^\-\-help$") != ""  ]]; then
     usage
     exit 0
 fi
 
 # 引数が"アカウント/ディレクトリ"か"ディレクトリのみ"かを判定する
-set +e
+set +eu
 TAG_NAME=$(echo $1 | grep "/")
-set -e
 MOUNT_DIR=$2
-set -u
+set -eu
 
 # 引数に / が含まれていれば、'/' の前後をアカウント名とディレクトリ名に分ける
 if [ -n "${TAG_NAME}" ]; then
@@ -48,9 +64,9 @@ fi
 
 # 指定したディレクトリが存在するか確認する
 if [ ! -d "${EXEC_DIR}/${IMAGE_DIR}" ]; then
-    echo -e "ERROR: No such directory : ${IMAGE_DIR}\n" >&2;
+    echo -e "\e[31merror: \e[37mディレクトリが見つかりません。 ${IMAGE_DIR}\e[m" >&2;
     usage
-    echo -e "\nPlease select a directory from the following list:"
+    echo -e "\e[37m次のディレクトリを指定してください。\e[m" >&2;
     # ディレクトリのリストを表示する
     ls -1F | grep -E "^.+\/$" | sed -E "s|(.+)/$|    \1|g"
     exit 1
diff --git a/image-build b/image-build
--- a/image-build
+++ b/image-build
@@ -2,7 +2,23 @@
 
 #-----------------------------------------------------------------------------
 function usage () {
-    echo "$(basename $0) <Dockerfile directory> ..." 2>&1;
+echo -e "
+使い方: image-build [OPTION]... TAG
+任意のイメージを作成します。
+例: image-build -u 'user' brew-base
+
+\e[33;1m引数:
+    \e[32mTAG
+        \e[37mイメージタグを指定します。
+        DockerHub のアカウント名を使用する形式（'account/tag'）
+        もしくはタグ名のみの形式（'tag'）を指定することができます。
+
+\e[33;1mオプション:
+    \e[32m-u\e[37m, \e[32m--user <ユーザー名>
+        \e[37m省略可。コンテナで使用するユーザー名を指定します。
+        省略した場合は、現在のホスト側ユーザー名が指定されます。
+\e[m
+" 2>&1;
 }
 
 #-----------------------------------------------------------------------------
@@ -10,10 +26,21 @@ function usage () {
 # $1 : DockerHub アカウント名(省略可）/ Dockerfile のあるディレクトリ
 # 例 : xxx/brew-base or brew-base
 #-----------------------------------------------------------------------------
-
 DOCKER_BULDKIT=1
 
 EXEC_DIR=$(cd $(dirname $0) && pwd)
+
+if [ $# -eq 0 ]; then
+    echo -e "\e[31merror: \e[37m少なくとも1つの引数が必要です。\e[m" >&2;
+    usage
+    exit 1
+fi
+
+# 引数がヘルプオプションだけであれば、ヘルプを表示して終了する
+if [ $(echo $1 | grep -E "^\-h|^\-\-help$") != ""  ]; then
+    usage
+    exit 0
+fi
 
 set +eu
 # 引数が"アカウント/ディレクトリ"か"ディレクトリのみ"かを判定する
@@ -40,9 +67,9 @@ fi
 
 # 指定したディレクトリが存在するか確認する
 if [ ! -d "${EXEC_DIR}/${IMAGE_DIR}" ]; then
-    echo -e "ERROR: No such directory : ${IMAGE_DIR}\n" >&2;
+    echo -e "\e[31merror: \e[37mディレクトリが見つかりません。 ${IMAGE_DIR}\e[m" >&2;
     usage
-    echo -e "\nPlease select a directory from the following list:"
+    echo -e "\e[37m次のディレクトリを指定してください。\e[m" >&2;
     # ディレクトリのリストを表示する
     ls -1F | grep -E "^.+\/$" | sed -E "s|(.+)/$|    \1|g"
     exit 1
